### ISSUE TITLE
pagedown_init does not work with Rails 4's turbolinks

### ISSUE THREAD

**Issue by andrewcsmith** [hughevans/pagedown-bootstrap-rails#14]
Rails 4's turbolinks short-circuit the jquery ready call in pagedown_init. Clicking "edit" on my blog posts now brings up a textarea without pagedown enabled; when I refresh the page, however, the pagedown controls appear.

[This stackoverflow answer](http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links) suggests using this format instead:

    ready = -> ...
    (...code here...)
    $(document).ready(ready)
    $(document).on('page:load', ready)

If that looks good I'll submit a pull request.

**Comment by hughevans** [comment]
Thanks @andrewcsmith. I just tested Turbolinks with `jquery.turbolinks` and that works well. Suggest either using that or writing your own initialiser.

I’ll add a note in the README. Cheers!
