### ISSUE TITLE
 I want to change the position of the preview

### ISSUE THREAD

**Issue by sagaekeiga** [hughevans/pagedown-bootstrap-rails#18]
Nice to meet you.

My name is KeigaSagae.
I am Japanese.
Pagedown-bootstrap-rails is a very convenient function.

By the way,I want to change the position of the preview.

【Current status】
There is a preview under the editor.

【Ideal】
There is a preview on the right of the editor.

Please tell me how to do it.

**Comment by hughevans** [comment]
Ohayo @sagaekeiga,

You just need a HTML `div` with the correct ID:

```erb
<div id="wmd-preview-<%= attribute_name_goes_here %>" class="wmd-preview"></div>
```

Regards,
Hugh

**Comment by sagaekeiga** [comment]
Thank you!!
You are a genius!!
